### Input
# reference rgba images folder's path (default to None, can be load in cmd too)
reference: "Images_enhanced"
# input mesh for stage 2 (auto-search from stage 1 output path if None)
mesh:
# estimated elevation angle for input image 
elevation: 0
# camera azimuth angle of the first reference image
init_angle: 0
# reference image resolution
ref_size_H: 1024
ref_size_W: 1024
# 
persistent_folder: "BlenderAI3D"
#
persistent_inputs_folder: "Inputs"
#
persistent_meshes_folder: "Meshes"
#
persistent_outputs_folder: "Outputs"
#
mesh_name: "untitled.obj"
#
saved_mesh_name: "untitled_saved.obj"

### Output
outdir: logs
mesh_format: obj
save_path: save

### Training
### Training
# training iterations for 3DGS
iters: 100000
# weight for d-ssim loss
lambda_ssim: 0.5
# weight for lpips loss
lambda_lpips: 0
# training batch size per iter, value bigger than 1 helps to reduce the noise
batch_size: 5
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for refine texture
iters_refine: 30
# training camera radius
radius: 1.75
# training camera fovy
fovy: 49.1

# whether allow geom training in stage 2
train_geo: False

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 800
W: 800

### Textured Mesh
texture_lr: 0.1